# Generated by Django 2.2 on 2020-06-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pronunciation', '0002_auto_20200623_1151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audiofile',
            old_name='alternatives',
            new_name='transcript',
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='audio',
            field=models.FileField(upload_to='recorded_speech/'),
        ),
    ]
