# Generated by Django 2.2 on 2020-06-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pronunciation', '0003_auto_20200623_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='words',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='transcript',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
