# Generated by Django 2.2 on 2020-06-24 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pronunciation', '0004_auto_20200623_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypedAlteration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integer_start', models.SmallIntegerField()),
                ('integer_finish', models.SmallIntegerField()),
                ('words_to_be_deleted', models.CharField(blank=True, max_length=200, null=True)),
                ('words_to_be_inserted', models.CharField(blank=True, max_length=200, null=True)),
                ('url', models.CharField(blank=True, max_length=200, null=True)),
                ('visemes', models.CharField(blank=True, max_length=4000, null=True)),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pronunciation.AudioFile')),
            ],
        ),
    ]
