# Generated by Django 2.2 on 2020-05-29 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SynthesisedSpeech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pitch', models.SmallIntegerField(blank=True, null=True)),
                ('voice', models.CharField(blank=True, max_length=20, null=True)),
                ('emotion', models.CharField(blank=True, max_length=20, null=True)),
                ('text', models.CharField(blank=True, max_length=500, null=True)),
                ('visemes', models.CharField(blank=True, max_length=10000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
