//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.11
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum CPRCTHD_CUE {
  CPRC_CUE_ERROR = 0,
  CPRC_CUE_OK = 1,
  CPRC_CUE_RESTART = 2
}
