//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.11
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum CPRC_SC_STAT {
  CPRC_SC_WAITING = 0,
  CPRC_SC_PLAYING_MID = 1,
  CPRC_SC_PLAYING_LAST_FRAME = 2,
  CPRC_SC_PLAYED = 3
}
