//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.11
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum CPRC_SC_CHANNEL {
  CPRC_SC_MONO = 0,
  CPRC_SC_STEREO = 1
}
